export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS ';
export const LOAD_MORE_PHONES_FAIL = 'LOAD_MORE_PHONES_START';

export const FETCH_PHONE_BY_ID_START = 'FETCH_PHONE_BY_ID_START';
export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS';
export const FETCH_PHONE_BY_ID_FAIL = 'FETCH_PHONE_BY_ID_FAIL';

export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET';